package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.ProductShoppingcart;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProductShoppingcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT_SHOPPINGCART
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    int insert(ProductShoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT_SHOPPINGCART
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    List<ProductShoppingcart> selectAll();
}