package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Product;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCT
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int updateByPrimaryKey(Product record);
}