package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Shoppingcart;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ShoppingcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int insert(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    Shoppingcart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    List<Shoppingcart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Thu Apr 27 21:35:59 EEST 2023
     */
    int updateByPrimaryKey(Shoppingcart record);
}