package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Shoppingcart;

import javax.enterprise.inject.Model;
import java.util.List;
@Model
public interface ShoppingcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Fri Apr 28 01:11:48 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Fri Apr 28 01:11:48 EEST 2023
     */
    int insert(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Fri Apr 28 01:11:48 EEST 2023
     */
    Shoppingcart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Fri Apr 28 01:11:48 EEST 2023
     */
    List<Shoppingcart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPPINGCART
     *
     * @mbg.generated Fri Apr 28 01:11:48 EEST 2023
     */
    int updateByPrimaryKey(Shoppingcart record);
}