package lt.vu.mybatis.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @return the value of PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ADDRESS
     *
     * @param address the value for PUBLIC.CUSTOMER.ADDRESS
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.BIRTHDATE
     *
     * @return the value of PUBLIC.CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.BIRTHDATE
     *
     * @param birthdate the value for PUBLIC.CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @return the value of PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @param name the value for PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}