package lt.vu.mybatis.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.DISCOUNT
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    private Integer optLockVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.ID
     *
     * @return the value of PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.ID
     *
     * @param id the value for PUBLIC.PRODUCT.ID
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @return the value of PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.DESCRIPTION
     *
     * @param description the value for PUBLIC.PRODUCT.DESCRIPTION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @return the value of PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.NAME
     *
     * @param name the value for PUBLIC.PRODUCT.NAME
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.DISCOUNT
     *
     * @return the value of PUBLIC.PRODUCT.DISCOUNT
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.DISCOUNT
     *
     * @param discount the value for PUBLIC.PRODUCT.DISCOUNT
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.PRODUCT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun May 21 18:28:12 EEST 2023
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }
}