package lt.vu.mybatis.model;

public class ProductShoppingcart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT_SHOPPINGCART.PRODUCT_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCT_SHOPPINGCART.SHOPPINGCARTS_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    private Integer shoppingcartsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT_SHOPPINGCART.PRODUCT_ID
     *
     * @return the value of PUBLIC.PRODUCT_SHOPPINGCART.PRODUCT_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT_SHOPPINGCART.PRODUCT_ID
     *
     * @param productId the value for PUBLIC.PRODUCT_SHOPPINGCART.PRODUCT_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCT_SHOPPINGCART.SHOPPINGCARTS_ID
     *
     * @return the value of PUBLIC.PRODUCT_SHOPPINGCART.SHOPPINGCARTS_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public Integer getShoppingcartsId() {
        return shoppingcartsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCT_SHOPPINGCART.SHOPPINGCARTS_ID
     *
     * @param shoppingcartsId the value for PUBLIC.PRODUCT_SHOPPINGCART.SHOPPINGCARTS_ID
     *
     * @mbg.generated Wed Apr 26 06:03:46 EEST 2023
     */
    public void setShoppingcartsId(Integer shoppingcartsId) {
        this.shoppingcartsId = shoppingcartsId;
    }
}